#!/bin/sh -f

app=exlib_sg

echo "NOTE : jks password is 'android'"

build_debug=no
build_verbose=no
build_set_x=no

build_ndk=yes
build_java=yes
build_sign=yes # due to a bug in SDK 22 and Android 2.2
build_sign=no
build_install=yes

build_pwd=android

while test $# -ge 1 ; do
  case $1 in
    -g) build_debug=yes;;
    -x) build_set_x=yes;;
    -v) build_verbose=yes;;
    -java) build_ndk=no;build_sign=no;build_install=no;;
    -i)    build_ndk=no;build_java=no;build_sign=no;;
    -*) echo "unknwon option : $1" ; exit ;;
  esac
  shift
done

if [ ${build_set_x} = "yes" ] ; then set -x; fi

save_dir=`pwd`

cd ..

if [ ${build_ndk} = "yes" ] ; then
  if [ ${build_verbose} = "yes" ] ; then
    ndk-build V=1
  else
    ndk-build
  fi
fi

target=release
if [ ${build_debug} = "yes" ] ; then target=debug;fi

if [ ${build_java} = "yes" ] ; then ant ${target}; fi

if [ ${build_sign} = "yes" ] ; then
  /bin/cp ./bin/${app}-${target}-unsigned.apk ./bin/${app}-${target}-unaligned.apk
  jarsigner -keystore ./${app}.jks -storepass ${build_pwd} -keypass ${build_pwd} ./bin/${app}-${target}-unaligned.apk ${app}
  zipalign -f 4 ./bin/${app}-${target}-unaligned.apk ./bin/${app}-${target}.apk
fi

if [ ${build_install} = "yes" ] ; then
  adb install -r ./bin/${app}-${target}.apk
fi

cd ${save_dir}
